#!/bin/bash

# bash script to generate a gnuplot script to make a movie 
MAX=200
echo "clear" > plot.gpi
echo "reset" >> plot.gpi
echo "set terminal gif animate delay 10 font \"/Library/Fonts/Georgia.ttf, 11\"" >> plot.gpi
echo "set pm3d map" >>plot.gpi
echo "set palette color" >>plot.gpi
echo "set cbrange [0:2]" >>plot.gpi
echo "set output \"animate.gif\"" >> plot.gpi
echo "set ticslevel 0.8" >>plot.gpi
echo "set xrange [-10:10]" >> plot.gpi
echo "set yrange [-10:10]" >> plot.gpi
echo "set isosample 40,40" >> plot.gpi

# echo "set hidden3d" >> plot.gpi
for ((i=0;i<${MAX};i++))
do
echo "splot 'wft' not index $i"; done >> plot.gpi

